### ISSUE TITLE
Upgrade project/build.properties to use SBT 1.9.0

### ISSUE THREAD

**Issue by ScalaWilliam** [sbt/sbt-jmh#219]
Now that SBT 1.9.0 is released, would it be possible to release this plugin with this version of SBT? This would make it available to thousands of developers who are desperate to benefit from easy performance benchmarking in Scala & Java with SBT :-)

Thanks so much!

**Comment by guizmaii** [comment]
FYI https://github.com/sbt/sbt-jmh/pull/220

**Comment by guizmaii** [comment]
FYI, @johanandren released v0.4.5 with sbt 1.9.0

Thanks for your reactivity @johanandren! ❤️
