### ISSUE TITLE
Move this repo under sbt/sbt-jmh

### ISSUE THREAD

**Issue by ktoso** [sbt/sbt-jmh#28]
The "more official place" for sbt plugins.
And add it to the list on the sbt site as well.

**Comment by SethTisue** [comment]
@ktoso I assume you're less interested in maintaining this these days :-)

would you agree to transferring it to the sbt org? if so, I think @eed3si9n could work with you to make it happen

**Comment by eed3si9n** [comment]
If you transfer the ownership to me, I can move it to sbt org and make a team with you and whoever you want in it.

**Comment by ktoso** [comment]
> @ktoso I assume you're less interested in maintaining this these days :-)

Very interested but legally forbidden from doing so 😢 

Yeah I can add folks as owners, help is very welcome due to my unfortunate employer's rules about oss... Thanks! I'll add you both.

**Comment by ktoso** [comment]
And done!

Thanks @eed3si9n and @SethTisue. 
Sorry for the trouble from my end on the in-ability to maintain this nowadays...

**Comment by eed3si9n** [comment]
Repo is moved, and sbt-jmh is created with admin rights to this repo.

**Comment by SethTisue** [comment]
@ktoso this plugin is enormously valuable — thanks for the effort you put in on it, it's really helped a lot of people.

**Comment by ktoso** [comment]
Thanks a lot Seth, I'm very happy that it continues to be useful and maintained :) Thank you all
